### ISSUE TITLE
Scan other Composer dir

### ISSUE THREAD

**Issue by jeroenvermeulen** [fancyguy/composer-security-check-plugin#13]
Hi @sbuzonas,

We are a web hosting company.

Is it possible to install `fancyguy/composer-security-check-plugin` once on a server, use it to scan one of our customer's dirs? We don't wan't to change anything on the sites we host.

I tried the `-d` option but that does not work because the customer does not have the `audit` command defined.

**Comment by sbuzonas** [comment]
Global install of the plugin will allow you to run it anywhere.

I'm pretty sure I use the method of obtaining the composer file that the factory does. So using the environment variables the same way may work.

`COMPOSER=/path/to/composer-other.json`

**Comment by sbuzonas** [comment]
> Is it possible to install `fancyguy/composer-security-check-plugin` once on a server, use it to scan one of our customer's dirs? We don't wan't to change anything on the sites we host.

This was actually the exact use case I had in mind when I made the plugin.

**Comment by jeroenvermeulen** [comment]
I added some info here about the problem here: https://github.com/fancyguy/composer-security-check-plugin/pull/15#issuecomment-430134586
