### ISSUE TITLE
An error occurred: Could not resolve host: security.sensiolabs.org.  

### ISSUE THREAD

**Issue by gustawdaniel** [fancyguy/composer-security-check-plugin#20]
This is connected with https://github.com/sensiolabs/security-checker/issues/149

We need to replace https://security.sensiolabs.org/ by https://security.symfony.com/

**Comment by gustawdaniel** [comment]
I found command for this:

Install:

```
curl -sS https://get.symfony.com/cli/installer | bash
```

Use:

```
symfony security:check
```

**Comment by jeroenvermeulen** [comment]
While waiting for your PR to be merged you can use:
https://packagist.org/packages/magehost/composer-security-check-plugin

**Comment by sbuzonas** [comment]
@gustawdaniel @jeroenvermeulen thanks. I've been away from PHP dev for a while. New version 1.2.1 with the update.
